name: Deployment

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
          cache: npm

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        run: |
          try {
            if ((Get-WebSiteState -Name "DefaultAppPool").Value -eq "Started") {
              Stop-WebSite -Name "DefaultAppPool"
              Write-Output "Stopped Website DefaultAppPool"
            }
            if ((Get-WebAppPoolState -Name "DefaultAppPool").Value -eq "Started") {
              Stop-WebAppPool -Name "DefaultAppPool"
              Write-Output "Stopped Application Pool DefaultAppPool"
            }

            Start-Sleep -s 5

            $sourcePath = "C:\actions-runner\_work\Meintasty-fe\Meintasty-fe"
            $destinationPath = "C:\inetpub\wwwroot"

            # iisnode klasörünü hariç tutan Robocopy komutu
            robocopy $sourcePath $destinationPath /MIR /MT:16 /XD "iisnode"
            Write-Output "Files copied from $sourcePath to $destinationPath using Robocopy"

            if ((Get-WebSiteState -Name "DefaultAppPool").Value -eq "Stopped") {
              Start-WebSite -Name "DefaultAppPool"
              Write-Output "Started Website DefaultAppPool"
            }
            if ((Get-WebAppPoolState -Name "DefaultAppPool").Value -eq "Stopped") {
              Start-WebAppPool -Name "DefaultAppPool"
              Write-Output "Started Application Pool DefaultAppPool"
            }

            if ($lastexitcode -lt 8) { $global:lastexitcode = 0 }
          } catch {
            Write-Error "An error occurred during deployment: $_"
            exit 1
          }
